openapi: 3.0.3
info:
  title: Argovis API
  description: "REST API for Argo profiles, platforms, selections, BGC data, gridded\
    \ products, etc."
  contact:
    name: Argovis Collaboration
    url: https://argovis.colorado.edu/
    email: tbd@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: "0.1"
externalDocs:
  description: Find us on GitHub
  url: https://github.com/argovis/argovis_api
servers:
- url: https://argovis.colorado.edu
  description: "Server Hosted by University of Colorado, Boulder"
- url: http://localhost:3001
  description: Local server for testing and development
security:
- name: []
tags:
- name: ar
  description: atmospheric river shapes
- name: covar
  description: Argo float position forcast product
- name: tc
  description: tropical cyclone data
- name: grid
  description: "Gridded products derived from Argo floats, simulation, or satalite\
    \ product"
- name: metadata
  description: metadata-only queries
paths:
  /arShapes/findByDate:
    get:
      tags:
      - ar
      summary: shapes representing atmospheric rivers at a given date-time
      operationId: findARbyDate
      parameters:
      - name: date
        in: query
        description: three hour increments starting at 2004-01-01T00:00:00 and ending
          at 2017-04-02T03:00:00
        required: true
        style: form
        explode: true
        allowReserved: true
        schema:
          type: string
          format: date-time
          example: 2010-01-01T00:00:00Z
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Ar
  /arShapes/findByID:
    get:
      tags:
      - ar
      summary: shapes representing atmospheric rivers with a given ID
      operationId: findARbyID
      parameters:
      - name: _id
        in: query
        description: ID of an atmospheric river object
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 1_262992
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Ar
  /arShapes:
    get:
      tags:
      - ar
      summary: one instance of a shape representing an atmospheric river
      operationId: findOneAR
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arShapeSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Ar
  /covarGrid/{lat}/{lon}/{forcastDays}:
    get:
      tags:
      - covar
      summary: Probability distribution field for a float at point lat-lon after forcastDays.
      operationId: findCovar
      parameters:
      - name: lat
        in: path
        description: latitude (degrees) of Argo float location
        required: true
        style: simple
        explode: false
        schema:
          maximum: 90
          minimum: -90
          type: number
          example: 5.25
      - name: lon
        in: path
        description: longitude (degrees) of Argo float location
        required: true
        style: simple
        explode: false
        schema:
          maximum: 180
          minimum: -180
          type: number
          example: -20.33
      - name: forcastDays
        in: path
        description: number of days over which to project Argo float drift
        required: true
        style: simple
        explode: false
        schema:
          maximum: 1800
          minimum: 60
          type: number
          example: 60
          enum:
          - 60
          - 120
          - 140
          - 240
          - 360
          - 480
          - 720
          - 840
          - 960
          - 1080
          - 1200
          - 1320
          - 1440
          - 1560
          - 1680
          - 1800
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CovarSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Covar
  /tc:
    get:
      tags:
      - tc
      summary: one tropical cyclone instance
      operationId: findOneTC
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Tc
  /tc/findByDate:
    get:
      tags:
      - tc
      summary: tropical cyclones at a given date-time
      operationId: findTCbyDate
      parameters:
      - name: date
        in: query
        description: date-time formatted string
        required: true
        style: form
        explode: true
        allowReserved: true
        schema:
          type: string
          format: date-time
          example: 2010-01-01T00:00:00Z
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Tc
  /tc/findByDateRange:
    get:
      tags:
      - tc
      summary: tropical cyclones intersecting a time period
      operationId: findTCbyDateRange
      parameters:
      - name: startDate
        in: query
        description: date-time formatted string indicating the beginning of a time
          period
        required: true
        style: form
        explode: true
        allowReserved: true
        schema:
          type: string
          format: date-time
          example: 2010-01-01T00:00:00Z
      - name: endDate
        in: query
        description: date-time formatted string indicating the end of a time period
        required: true
        style: form
        explode: true
        allowReserved: true
        schema:
          type: string
          format: date-time
          example: 2010-01-01T00:00:00Z
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Tc
  /tc/stormNameList:
    get:
      tags:
      - tc
      summary: returns a list of tropical cyclone names and years
      operationId: findStormNameList
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Tc
  /tc/findByNameYear:
    get:
      tags:
      - tc
      summary: find a tropical cyclone by name and year
      operationId: findTCbyNameYear
      parameters:
      - name: name
        in: query
        description: name of tropical cyclone
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: LANE
      - name: year
        in: query
        description: year of tropical cyclone
        required: true
        style: form
        explode: true
        schema:
          type: number
          example: 2018
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tcSchema'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Tc
  /griddedProducts/gridMetadata:
    get:
      tags:
      - grid
      - metadata
      summary: "metadata from grid unique dates, pres levels"
      operationId: gridmeta
      parameters:
      - name: gridName
        in: query
        description: name of the gridded product
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: rgTempAnom
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GridMeta'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      x-swagger-router-controller: Grid
components:
  schemas:
    arShapeSchema:
      required:
      - _id
      - date
      - date_formatted
      - geoLocation
      - shapeID
      type: object
      properties:
        _id:
          type: string
        date:
          type: string
          format: date-time
        shapeId:
          type: integer
        geoLocation:
          $ref: '#/components/schemas/geoLocation'
        date_formateed:
          type: string
          format: date
      example:
        date: 2000-01-23T04:56:07.000+00:00
        date_formateed: 2000-01-23
        shapeId: 0
        geoLocation:
          coordinates:
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          type: type
        _id: _id
    CovarSchema:
      required:
      - _id
      - dLat
      - dLon
      - features
      - forcastDays
      - geoLocation
      type: object
      properties:
        features:
          type: array
          items:
            $ref: '#/components/schemas/CovarSchema_features'
        _id:
          type: string
        dLat:
          type: number
        dLon:
          type: number
        forcastDays:
          type: integer
        geoLocation:
          $ref: '#/components/schemas/geoLocation'
      example:
        features:
        - geometry:
            coordinates:
            - - 0.80082819046101150206595775671303272247314453125
              - 0.80082819046101150206595775671303272247314453125
            - - 0.80082819046101150206595775671303272247314453125
              - 0.80082819046101150206595775671303272247314453125
            type: type
          type: type
        - geometry:
            coordinates:
            - - 0.80082819046101150206595775671303272247314453125
              - 0.80082819046101150206595775671303272247314453125
            - - 0.80082819046101150206595775671303272247314453125
              - 0.80082819046101150206595775671303272247314453125
            type: type
          type: type
        dLat: 6.02745618307040320615897144307382404804229736328125
        geoLocation:
          coordinates:
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          type: type
        dLon: 1.46581298050294517310021547018550336360931396484375
        _id: _id
        forcastDays: 5
    tcSchema:
      required:
      - _id
      - endDate
      - num
      - source
      - startDate
      - year
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        num:
          type: number
        source:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        year:
          type: number
        trajData:
          type: array
          items:
            $ref: '#/components/schemas/tcSchema_trajData'
      example:
        endDate: 2000-01-23T04:56:07.000+00:00
        year: 6.02745618307040320615897144307382404804229736328125
        num: 0.80082819046101150206595775671303272247314453125
        name: name
        _id: _id
        source: source
        trajData:
        - date: date
          pres: 7.061401241503109105224211816675961017608642578125
          geoLocation:
            coordinates:
            - - 6.02745618307040320615897144307382404804229736328125
              - 6.02745618307040320615897144307382404804229736328125
            - - 6.02745618307040320615897144307382404804229736328125
              - 6.02745618307040320615897144307382404804229736328125
            type: type
          season: 9.301444243932575517419536481611430644989013671875
          lon: 5.63737665663332876420099637471139430999755859375
          time: 1.46581298050294517310021547018550336360931396484375
          class: class
          lat: 5.962133916683182377482808078639209270477294921875
          wind: 2.3021358869347654518833223846741020679473876953125
          timestamp: 2000-01-23T04:56:07.000+00:00
        - date: date
          pres: 7.061401241503109105224211816675961017608642578125
          geoLocation:
            coordinates:
            - - 6.02745618307040320615897144307382404804229736328125
              - 6.02745618307040320615897144307382404804229736328125
            - - 6.02745618307040320615897144307382404804229736328125
              - 6.02745618307040320615897144307382404804229736328125
            type: type
          season: 9.301444243932575517419536481611430644989013671875
          lon: 5.63737665663332876420099637471139430999755859375
          time: 1.46581298050294517310021547018550336360931396484375
          class: class
          lat: 5.962133916683182377482808078639209270477294921875
          wind: 2.3021358869347654518833223846741020679473876953125
          timestamp: 2000-01-23T04:56:07.000+00:00
        startDate: 2000-01-23T04:56:07.000+00:00
    GridMeta:
      required:
      - dates
      - maxDate
      - minDate
      - presLevels
      type: object
      properties:
        _id:
          type: string
        presLevels:
          type: array
          items:
            type: number
        dates:
          type: array
          items:
            type: string
            format: date-time
        minDate:
          type: string
          format: date-time
        maxDate:
          type: string
          format: date-time
      example:
        minDate: 2000-01-23T04:56:07.000+00:00
        dates:
        - 2000-01-23T04:56:07.000+00:00
        - 2000-01-23T04:56:07.000+00:00
        maxDate: 2000-01-23T04:56:07.000+00:00
        _id: _id
        presLevels:
        - 0.80082819046101150206595775671303272247314453125
        - 0.80082819046101150206595775671303272247314453125
    geoLocation:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            uniqueItems: true
            type: array
            items:
              maxItems: 2
              minItems: 2
              type: number
      example:
        coordinates:
        - - 6.02745618307040320615897144307382404804229736328125
          - 6.02745618307040320615897144307382404804229736328125
        - - 6.02745618307040320615897144307382404804229736328125
          - 6.02745618307040320615897144307382404804229736328125
        type: type
    errorResponse:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    CovarSchema_geometry:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: array
            items:
              maxItems: 2
              minItems: 2
              type: number
      example:
        coordinates:
        - - 0.80082819046101150206595775671303272247314453125
          - 0.80082819046101150206595775671303272247314453125
        - - 0.80082819046101150206595775671303272247314453125
          - 0.80082819046101150206595775671303272247314453125
        type: type
    CovarSchema_features:
      type: object
      properties:
        geometry:
          $ref: '#/components/schemas/CovarSchema_geometry'
        type:
          type: string
      example:
        geometry:
          coordinates:
          - - 0.80082819046101150206595775671303272247314453125
            - 0.80082819046101150206595775671303272247314453125
          - - 0.80082819046101150206595775671303272247314453125
            - 0.80082819046101150206595775671303272247314453125
          type: type
        type: type
    tcSchema_trajData:
      required:
      - class
      - date
      - geoLocation
      - lat
      - lon
      - time
      - timestamp
      type: object
      properties:
        date:
          type: string
        time:
          type: number
        class:
          type: string
        lat:
          type: number
        lon:
          type: number
        wind:
          type: number
        pres:
          type: number
        season:
          type: number
        timestamp:
          type: string
          format: date-time
        geoLocation:
          $ref: '#/components/schemas/geoLocation'
      example:
        date: date
        pres: 7.061401241503109105224211816675961017608642578125
        geoLocation:
          coordinates:
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          - - 6.02745618307040320615897144307382404804229736328125
            - 6.02745618307040320615897144307382404804229736328125
          type: type
        season: 9.301444243932575517419536481611430644989013671875
        lon: 5.63737665663332876420099637471139430999755859375
        time: 1.46581298050294517310021547018550336360931396484375
        class: class
        lat: 5.962133916683182377482808078639209270477294921875
        wind: 2.3021358869347654518833223846741020679473876953125
        timestamp: 2000-01-23T04:56:07.000+00:00
  responses:
    badRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    notFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    serverError:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
  parameters:
    arDate:
      name: date
      in: query
      description: three hour increments starting at 2004-01-01T00:00:00 and ending
        at 2017-04-02T03:00:00
      required: true
      style: form
      explode: true
      allowReserved: true
      schema:
        type: string
        format: date-time
        example: 2010-01-01T00:00:00Z
    arID:
      name: _id
      in: query
      description: ID of an atmospheric river object
      required: true
      style: form
      explode: true
      schema:
        type: string
        example: 1_262992
    date:
      name: date
      in: query
      description: date-time formatted string
      required: true
      style: form
      explode: true
      allowReserved: true
      schema:
        type: string
        format: date-time
        example: 2010-01-01T00:00:00Z
    startDate:
      name: startDate
      in: query
      description: date-time formatted string indicating the beginning of a time period
      required: true
      style: form
      explode: true
      allowReserved: true
      schema:
        type: string
        format: date-time
        example: 2010-01-01T00:00:00Z
    endDate:
      name: endDate
      in: query
      description: date-time formatted string indicating the end of a time period
      required: true
      style: form
      explode: true
      allowReserved: true
      schema:
        type: string
        format: date-time
        example: 2010-01-01T00:00:00Z
    gridNameUniform:
      name: gridName
      in: query
      description: name of the gridded product
      required: true
      style: form
      explode: true
      schema:
        type: string
        example: rgTempAnom
    lat:
      name: lat
      in: path
      description: latitude (degrees) of Argo float location
      required: true
      style: simple
      explode: false
      schema:
        maximum: 90
        minimum: -90
        type: number
        example: 5.25
    lon:
      name: lon
      in: path
      description: longitude (degrees) of Argo float location
      required: true
      style: simple
      explode: false
      schema:
        maximum: 180
        minimum: -180
        type: number
        example: -20.33
    forcastDays:
      name: forcastDays
      in: path
      description: number of days over which to project Argo float drift
      required: true
      style: simple
      explode: false
      schema:
        maximum: 1800
        minimum: 60
        type: number
        example: 60
        enum:
        - 60
        - 120
        - 140
        - 240
        - 360
        - 480
        - 720
        - 840
        - 960
        - 1080
        - 1200
        - 1320
        - 1440
        - 1560
        - 1680
        - 1800
